version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: expense-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - expense-network

  backend:
    build: ./Application-Code/backend
    container_name: expense-backend
    restart: always
    ports:
      - "3500:3500"
    environment:
      - MONGO_CONN_STR=mongodb://mongodb:27017/expensetracker
      - PORT=3500
    depends_on:
      - mongodb
    networks:
      - expense-network

  frontend:
    build: ./Application-Code/frontend
    container_name: expense-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3500/api/expenses
    depends_on:
      - backend
    networks:
      - expense-network

volumes:
  mongodb_data:

networks:
  expense-network:
    driver: bridge