apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-tracker
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/expense-backend:latest
        ports:
        - containerPort: 3500
        env:
        - name: MONGO_CONN_STR
          value: "mongodb://mongodb-service:27017/expensetracker"
        - name: PORT
          value: "3500"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense-tracker
spec:
  selector:
    app: backend
  ports:
  - port: 3500
    targetPort: 3500
  type: ClusterIP